apiVersion: v2
appVersion: 0.12.0
description: A Helm chart for Kubernetes
name: lmrdashboard
type: application
version: 0.12.0
dependencies:
  - name: mariadb
    version: '9.0.1'
    repository: 'https://charts.bitnami.com/bitnami'
